**def line():
    print("TO DO")
a=float(imput("ingrese el coeficiente A: "))
b=float(imput("ingrese el coeficiente B: "))
X1=float(imput("ingrese el coeficiente X1: "))
X2=float(imput("ingrese el coeficiente X2: "))
Y1=(AX1+B)
Y2=(AX2+B)
distancia=(sqrt((X2-X1)**2+(Y2-Y1)**2))
print("la distancia es: ", distancia)
